### PR TITLE
Adding arguments to support linear bootstrapping in tab_model and tidies

### PR DESCRIPTION
**Pull request by AmirDJV**
This pull request correspond to [issue 571](https://github.com/strengejacke/sjPlot/issues/571) - Adding bootstrapping as an option in `tab_model()`.

### CODE REVIEW

**Comment by strengejacke** [comment]
Thanks, looks good! Feel free to add yourself as contributor the the description file.

**Comment by AmirDJV** [comment]
Not sure what you mean. You meant this?

**Comment by strengejacke** [comment]
> Not sure what you mean. You meant this?

Yes!

Note that you have two closing parantheses, but just need one (due to the missing ORICD), see failing checks: https://travis-ci.org/strengejacke/sjPlot/jobs/617134659#L297

So you just need to remove the 2nd closing paranthesis in your author line, than all checks should pass (and then I can merge).

**Comment by AmirDJV** [comment]
Thank you! :-)

**Pull request merged**
