### PR TITLE
Add option 'notch = TRUE' to (grouped) box and violin plots (closes #304)

### LINKED ISSUE #304: Feature Request: sjp.frq/grpfrq -- add option to set 'notch = TRUE' for boxplots
I would like to use notched boxplots (i.e., `geom_boxplot(notch = TRUE`),  but this option doesn't seem to be implemented yet.

If you'd decide to implement it, you could just use the (at the moment unused for boxplot) option `show.ci = TRUE`...

Thanks!

### PR DESCRIPTION
**Pull request by januz**
I went ahead and tried to implement my requested changes myself. From my testing, it seems to work as expected/requested. Hope you'll consider this useful!

### CODE REVIEW

**Comment by strengejacke** [comment]
You don't need to switch via `if()`-statement. You could simply add `notch = show.ci` in the code.

**Comment by januz** [comment]
Ha, that's true, sorry... I committed the changes.

**Comment by strengejacke** [comment]
close #304

**Comment by strengejacke** [comment]
Thanks! Merged now.

**Pull request merged**
