### PR TITLE
New function plot_likert_grp.R

### PR DESCRIPTION
**Pull request by ndevln**
Hello Daniel,

since your `sjt.itemanalysis` function has grouping functionality, I developed a function to plot the likert scales in the same way. I have tried to transform this function that it is consistent with other sjPlot functions, especially `sjt.itemanalysis` and `plot_likert`.

In the standard use case my function will behave exactly as `sjt.itemanalysis `. You provide a data.frame with items ans columns and a vector with group membership. This can be done either by hand or by using `sjt.pca`.

```
data(efc)
plot_data <- find_var(efc, pattern = "cop", out = "df")
plot_likert_grp(plot_data, c(2,1,1,1,1,2,2,2,1))
```
Result:
image

Most `plot_likert` options are available and I added better legend positioning, since in most cases one legend is enough.
```
plot_likert_grp(plot_data, 
                c(rep("B",4),rep("A",5)), 
                sort.groups = F, 
                grid.range = c(0.9,1.1), 
                geom.colors = "RdBu", 
                rel_heights = c(6,8), 
                wrap.labels = 40, 
                reverse.scale=T)
```

image

I tried to match your coding style and variable naming to reduce the maintenance burden.

The biggest downside is the new dependency **cowplot**. `sjPlot::plot_grid` did not provide enough functionality. Cowplot provides labelling, which is nice. But the most important feature is `rel_heights`. This allows to scale the subplots to have same height bars on all plots. It's not perfect since it has to be done by hand, maybe there is an automatic way in the future.

Also, there is a if statement hell on line 100 to 105. Maybe I will find a way to reorder or split up the statements in the future.

Greetings
Alex

### CODE REVIEW

**Comment by strengejacke** [comment]
I like the idea of having grouped likert bars, but actually I would try to integrate this into the existing `plot_likert()`, with an optional grouping-argument. If `NULL`, the regular plot_likert is called, if not NULL, it internally calls plot_likert_grp (or similar, maybe it can even be integrated into plot_likert).

**Comment by ndevln** [comment]
My idea to integrate it, would be to move the current function into a helper function named .plot_likert() which handles the actual plotting. My function would be the function you call with plot_likert() and I would integrate likert plots without grouping in the same way, as you did in sjt.itemanalyses(). 

All cowplot options would be collapsed into a list, which is passed to the function as cowplot.options = list().

Would this design be ok for you? Or is there another function which design I should copy?

**Comment by strengejacke** [comment]
That sounds good!

**Comment by ndevln** [comment]
Here is the combined solution. Single and multi group likert plots are working. The current `plot_likert ` function was moved to `.plot_likert` and is untouched. The new parent function passes all options, which are currently available, on to `.plot_likert`. Function behaviour for single/ungrouped likert plots should be unchanged (or is unchanged according to my tests). The Documentation was updated.

For testing single group behaviour, I used the testing code of the last 2 pull request. The code in this pull request can be used when dropping the "_grp" suffix (see below).

The new dependency `cowplot` is still optional and only demanded if groups are used. Maybe it should be added to suggested.

I hope you like it :)

```
plot_likert(plot_data, c(2,1,1,1,1,2,2,2,1))
plot_likert(plot_data, 
                c(rep("B",4),rep("A",5)), 
                sort.groups = F, 
                grid.range = c(0.9,1.1), 
                geom.colors = "RdBu", 
                rel_heights = c(6,8), 
                wrap.labels = 40, 
                reverse.scale=T)
```

**Comment by ndevln** [comment]
rebase :)

The new plot_likert is in use on our rstudio server. So far nor problems.

**Comment by strengejacke** [comment]
Thanks, I'll look at this later. First, a package release is planned, which will also be used by sjPlot, so I'll get back to this probably by the end of April or beginning of May, and it should go into the next sjPlot-update.

**Comment by ndevln** [comment]
FYI: The package "performance" is not on CRAN. This results in an installation failure. I had to revert c61d096 for updating.

**Comment by strengejacke** [comment]
> The package "performance" is not on CRAN

That was the package I was talking about when I said a package release is planned. ;-)

**Comment by strengejacke** [comment]
Ok, I slightly revised the docs, but this PR should be ready to merge now.

**Comment by strengejacke** [comment]
I think I'll rename the argument `factor.groups` to `groups`, since it must not necessarily be "factors".

**Pull request merged**
